//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Student_recordsEntities : DbContext
    {
        public Student_recordsEntities()
            : base("name=Student_recordsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_Bio> Student_Bio { get; set; }
        public virtual DbSet<Student_marks> Student_marks { get; set; }
        public virtual DbSet<Student_Userdetails> Student_Userdetails { get; set; }
    }
}
