//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Bio
    {
        public string Username { get; set; }
        public string DOB { get; set; }
        public string Department { get; set; }
    }
}
